name: Deploy to Render

# Trigger workflow on every push to main branch
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install Render CLI
      - name: Install Render CLI
        run: |
          curl -L https://cdn.renderyourapp.com/cli/latest/install.sh | bash
          echo "$HOME/.render/bin" >> $GITHUB_PATH

      # Step 3: Login to Render using API key
      - name: Render login
        run: render login --api-key ${{ secrets.RENDER_API_KEY }}

      # Step 4: Deploy Docker container to Render service
      - name: Deploy Docker to Render
        run: |
          render services update ${{ secrets.RENDER_SERVICE_ID }} \
          --branch main \
          --dockerfile ./Dockerfile \
          --no-cache
